// frontend/src/components/ui/progress-bar.tsx
import { cn } from "@/lib/utils";

interface ProgressBarProps {
  value: number;
  max?: number;
  className?: string;
  showLabel?: boolean;
  size?: "sm" | "md" | "lg";
}

export function ProgressBar({ 
  value, 
  max = 100, 
  className, 
  showLabel = true,
  size = "md" 
}: ProgressBarProps) {
  const percentage = Math.min(Math.max((value / max) * 100, 0), 100);
  
  const getColor = (percent: number) => {
    if (percent >= 80) return "bg-success";
    if (percent >= 50) return "bg-warning";
    return "bg-destructive";
  };

  const sizeClasses = {
    sm: "h-2",
    md: "h-3",
    lg: "h-4"
  };

  return (
    <div className={cn("w-full", className)}>
      {showLabel && (
        <div className="flex justify-between items-center mb-2">
          <span className="text-sm font-medium text-muted-foreground">
            Compliance Score
          </span>
          <span className="text-sm font-semibold">
            {percentage.toFixed(0)}%
          </span>
        </div>
      )}
      <div className={cn(
        "w-full bg-muted rounded-full overflow-hidden",
        sizeClasses[size]
      )}>
        <div
          className={cn(
            "h-full transition-all duration-300 ease-out rounded-full",
            getColor(percentage)
          )}
          style={{ width: `${percentage}%` }}
        />
      </div>
    </div>
  );
}

// frontendv2/src/lib/components/ui/progress-bar/progress-bar.svelte
<script lang="ts">
	import { cn } from '$lib/utils';

	interface Props {
		className?: string;
		value?: number;
		size?: 'sm' | 'md' | 'lg';
	}

	let { className = '', value = 0, size = 'md', ...restProps }: Props = $props();

	const sizes = {
		sm: 'h-2',
		md: 'h-3',
		lg: 'h-4'
	};

	let percentage = $derived(Math.min(100, Math.max(0, value)));
</script>

<div
	class={cn(
		'relative w-full overflow-hidden rounded-full bg-secondary',
		sizes[size],
		className
	)}
	{...restProps}
>
	<div
		class="h-full w-full flex-1 bg-primary transition-all duration-300 ease-in-out"
		style="transform: translateX(-{100 - percentage}%)"
	></div>
</div>
